### ISSUE TITLE
Is this project sunsetting?

### ISSUE THREAD

**Issue by jmatsu** [kibela/kibela-api-v1-document#72]
Could you please explain the context of the [message](https://github.com/kibela/kibela-api-v1-document/blob/23dbeeae7bb7d739f9ee7292b309d9cfa67cc6ca/schema.graphql#L3)? What action will we have to take after the deadline? We couldn't find any announcement for the context.

**Comment by moeki0** [comment]
The [message](https://github.com/kibela/kibela-api-v1-document/blob/23dbeeae7bb7d739f9ee7292b309d9cfa67cc6ca/schema.graphql#L3) means we are discontinuing the management of the **`schema.graphql` file only**. This repository (README) and API are not sunsetting. 

We have determined that managing with a static file like `schema.graphql` is not suitable since the GraphQL schema changes depending on the user who uses it.

After the deadline, please [refer to the schema via the API console](https://github.com/kibela/kibela-api-v1-document#%E3%83%AA%E3%83%95%E3%82%A1%E3%83%AC%E3%83%B3%E3%82%B9%E3%83%9E%E3%83%8B%E3%83%A5%E3%82%A2%E3%83%AB).

**Comment by jmatsu** [comment]
Got it. Thanks for your support.
